services:
  db:
    image: postgres:16
    container_name: commerce_core_db_kotlin
    restart: unless-stopped
    environment:
      POSTGRES_DB: commerce_core_db
      POSTGRES_USER: commerce_user
      POSTGRES_PASSWORD: commerce_pass
    ports:
      - "5434:5432"
    volumes:
      - commerce_core_postgres_data:/var/lib/postgresql/data

volumes:
  commerce_core_postgres_data: